<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'prettyroutes_acf_group_60a72e436d9b0',
		'title' => 'Route Options',
		'fields' => array(
			array(
				'key' => 'prettyroutes_acf_field_60ade50d7a35d',
				'label' => 'Route Map',
				'name' => '_route_map',
				'type' => 'relationship',
				'instructions' => 'Choose the map where you would like to show this route.',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'map',
					1 => 'route_map',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a72e756cd4a',
				'label' => 'Type',
				'name' => '_route_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'road' => 'Road',
					'offroad' => 'Offroad',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a72ed06cd4b',
				'label' => 'Route Color',
				'name' => '_route_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#00AAFF',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a861ee106d1',
				'label' => 'Route',
				'name' => 'route',
				'type' => 'prettyroutes_route',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'font_size' => 14,
				'lattitude' => '-37.847097612887985',
				'longitude' => '144.97131142516656',
				'zoom_level' => 7,
			),
			array(
				'key' => 'prettyroutes_acf_field_60a72f3c6cd4c',
				'label' => 'From (Origin)',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 1,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'prettyroutes_acf_field_60a72f606cd4d',
				'label' => 'Display Pinpoint',
				'name' => '_route_origin_pin_enabled',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a72fa16cd4e',
				'label' => 'Enable Tooltip',
				'name' => '_route_origin_tooltip_enabled',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a72fcb6cd4f',
				'label' => 'Close Tooltip',
				'name' => '_route_origin_tooltip_close',
				'type' => 'select',
				'instructions' => '<b>Automatically:</b> This will cause the tooltip to automatically hide when the user hovers off the location.<br><b>Manually:</b> Good if you want to add links to the tooltip.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'auto' => 'Automatically',
					'manual' => 'Manually',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a7303a6cd50',
				'label' => 'Tooltip',
				'name' => '_route_origin_tooltip_content',
				'type' => 'textarea',
				'instructions' => 'This is the brief text that appears in the tooltip when a user hovers over this location. You may use basic html text formatting, such as &lt;br&gt;, &lt;i&gt;, etc.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a7314bb0270',
				'label' => 'Pin Image',
				'name' => '_route_origin_pin',
				'type' => 'image',
				'instructions' => 'You may select a custom pin image to be used for this location only. Leave blank to use the dafault pin.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a77611c0834',
				'label' => 'Waypoints',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 1,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'prettyroutes_acf_field_60a7763dc0835',
				'label' => 'Detail Waypoints',
				'name' => 'acf_prettyroutes_waypoints',
				'type' => 'repeater',
				'instructions' => 'This field is based on above maps waypoints items. Add some waypoints on the map above and add theirs details here.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'row',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'prettyroutes_acf_field_60a77678c0836',
						'label' => 'Display Pinpoint',
						'name' => 'display_pinpoint',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'yes' => 'Yes',
							'no' => 'No',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'prettyroutes_acf_field_60a776c9c0838',
						'label' => 'Enable Tooltip',
						'name' => 'enable_tooltip',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'yes' => 'Yes',
							'no' => 'No',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'prettyroutes_acf_field_60a776e3c0839',
						'label' => 'Close Tooltip',
						'name' => 'close_tooltip',
						'type' => 'select',
						'instructions' => '<b>Automatically:</b> This will cause the tooltip to automatically hide when the user hovers off the location.<br>
	<b>Manually:</b> Good if you want to add links to the tooltip.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'auto' => 'Automatically',
							'manual' => 'Manually',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
					array(
						'key' => 'prettyroutes_acf_field_60a77725c083a',
						'label' => 'Tooltip',
						'name' => 'tooltip',
						'type' => 'textarea',
						'instructions' => 'This is the brief text that appears in the tooltip when a user hovers over this location. You may use basic html text formatting, such as &lt;br&gt;, &lt;i&gt;, etc.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => '',
					),
					array(
						'key' => 'prettyroutes_acf_field_60a77753c083b',
						'label' => 'Pin Image',
						'name' => 'pin_image',
						'type' => 'image',
						'instructions' => 'You may select a custom pin image to be used for this location only. Leave blank to use the dafault pin.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
			array(
				'key' => 'prettyroutes_acf_field_60a7333986386',
				'label' => 'To (Destination)',
				'name' => '',
				'type' => 'accordion',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'open' => 1,
				'multi_expand' => 1,
				'endpoint' => 0,
			),
			array(
				'key' => 'prettyroutes_acf_field_60a7334d86387',
				'label' => 'Display Pinpoint',
				'name' => '_route_destination_pin_enabled',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a7336686388',
				'label' => 'Enable Tooltip',
				'name' => '_route_destination_tooltip_enabled',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a7337b86389',
				'label' => 'Close Tooltip',
				'name' => '_route_waypoint_destination_tooltip_close',
				'type' => 'select',
				'instructions' => '<b>Automatically:</b> This will cause the tooltip to automatically hide when the user hovers off the location.<br><b>Manually:</b> Good if you want to add links to the tooltip.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'auto' => 'Automatically',
					'manual' => 'Manually',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a733b28638a',
				'label' => 'Tooltip',
				'name' => '_route_destination_tooltip_content',
				'type' => 'textarea',
				'instructions' => 'This is the brief text that appears in the tooltip when a user hovers over this location. You may use basic html text formatting, such as &lt;br&gt;, &lt;i&gt;, etc.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'prettyroutes_acf_field_60a733d38638b',
				'label' => 'Pin Image',
				'name' => '_route_destination_pin',
				'type' => 'image',
				'instructions' => 'You may select a custom pin image to be used for this location only. Leave blank to use the dafault pin.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'route',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
endif;