<?php

function crowd_get_default_values() {
	return array(
		'map_crowd_enabled'           => false,
		'map_crowd_require_approval'  => false,
		'map_crowd_thank_you_title'   => 'Submission Received. Thanks!',
		'map_crowd_thank_you_content' => 'We\'ve received your location! We will approve this soon and the location will be live on this map shortly, so be sure to check back soon. Thanks!',
	);
}

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'crowdmaps_acf_group_61d3c74e98ebd',
		'title' => 'MapifyPro Options',
		'fields' => array(
			array(
				'key' => 'crowdmaps_acf_field_61d3c76da17c5',
				'label' => 'Address Line 1',
				'name' => '_map_location_address',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'crowdmaps_acf_field_61d3c77aa17c6',
				'label' => 'Address Line 2',
				'name' => '_map_location_address_2',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'crowdmaps_acf_field_61d3c792a17c7',
				'label' => 'Tooltip',
				'name' => '_map_location_tooltip',
				'type' => 'textarea',
				'instructions' => 'This is the brief text that appears in the tooltip when a user hovers over this location. You may use basic html text formatting, such as &lt;br&gt;, &lt;i&gt;, etc.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map-location',
				),
				array(
					'param' => 'current_user_role',
					'operator' => '==',
					'value' => 'mpfy_contributor',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(array(
		'key' => 'crowdmaps_acf_group_60a5cf032f231',
		'title' => 'CrowdMaps',
		'fields' => array(
			array(
				'key' => 'crowdmaps_acf_field_60a5cf9a19c77',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'crowdmaps_acf_field_60a5cf1c19c75',
				'label' => 'Enable CrowdMaps',
				'name' => '_map_crowd_enabled',
				'type' => 'select',
				'instructions' => 'Enable CrowdMaps for this map',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'n' => 'No',
					'y' => 'Yes',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'crowdmaps_acf_field_60a5cf5e19c76',
				'label' => 'Require admin approval of submitted locations',
				'name' => '_map_crowd_require_approval',
				'type' => 'select',
				'instructions' => 'We suggest leaving this on as it will prevent spam and unwanted map locations. However, setting this to “No” will allow users to automatically add locations to the map without delay.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'n' => 'No',
					'y' => 'Yes',
				),
				'default_value' => 'y',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'crowdmaps_acf_field_60a5cfd819c78',
				'label' => 'Thank You Popup',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'crowdmaps_acf_field_60a5cfec19c79',
				'label' => 'Title',
				'name' => '_map_crowd_thank_you_title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Submission Received. Thanks!',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'crowdmaps_acf_field_60a5d00b19c7a',
				'label' => 'Content',
				'name' => '_map_crowd_thank_you_content',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'We\'ve received your location! We will approve this soon and the location will be live on this map shortly, so be sure to check back soon. Thanks!',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 11,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'crowdmaps_acf_group_61765ed90537c',
		'title' => 'CrowdMaps',
		'fields' => array(
			array(
				'key' => 'crowdmaps_acf_field_61765eead6e8c',
				'label' => 'MapifyPro Contributor',
				'name' => 'mpfy_contributor',
				'type' => 'user',
				'instructions' => 'If this map has been created by a CrowdMaps contributor, then his email will be showed here. The MapifyPro contributors are <a href="' . admin_url( 'users.php?role=mpfy_contributor' ) . '" target="_blank">listed here</a>.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'role' => array(),
				'allow_null' => 1,
				'multiple' => 0,
				'return_format' => 'id',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map-location',
				),
				array(
					'param' => 'current_user_role',
					'operator' => '!=',
					'value' => 'mpfy_contributor',
				),
			),
		),
		'menu_order' => 4,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
endif;