<?php
// List your URLs here
$urls = [
    'Http://www.Goby-design.com',
'http://www.mamazaraempandas.com',
'https://amzn.to/3CLGa42',
'https://amzn.to/3CLmCNg',
'https://amzn.to/3CMkbKn',
'https://amzn.to/3D7pk0N',
'https://amzn.to/3DaLiQq',
'https://amzn.to/3Dkr07v',
'https://amzn.to/3eEgoXz',
'https://amzn.to/3eHiztl',
'https://amzn.to/3eI99O2',
'https://amzn.to/3eItpz4',
'https://amzn.to/3eJK0To',
'https://amzn.to/3eM8wTM',
'https://amzn.to/3eNhiB2',
'https://amzn.to/3ESXaYI',
'https://amzn.to/3ET2onc',
'https://amzn.to/3EThZTM',
'https://amzn.to/3EV8h3d',
'https://amzn.to/3EViT25',
'https://amzn.to/3EWvuCi',
'https://amzn.to/3EYPDaO',
'https://amzn.to/3Fjybhg',
'https://amzn.to/3GFWjLK',
'https://amzn.to/3gjmJrF',
'https://amzn.to/3gkDjYm',
'https://amzn.to/3gkMnwh',
'https://amzn.to/3gkSG2O',
'https://amzn.to/3gnRvzO',
'https://amzn.to/3gsH4LJ',
'https://amzn.to/3gv9iFzc',
'https://amzn.to/3gxY6bd',
'https://amzn.to/3gzWMnS',
'https://amzn.to/3ioktR1',
'https://amzn.to/3jbS5BT',
'https://amzn.to/3MNZbYi',
'https://amzn.to/3MYAGYq',
'https://amzn.to/3s5Ls5w',
'https://amzn.to/3s8DNDr',
'https://amzn.to/3S9e6gA',
'https://amzn.to/3sc6Ndn',
'https://amzn.to/3SertMz',
'https://amzn.to/3Shchhw',
'https://amzn.to/3SkaVCO',
'https://amzn.to/3SkcHDY',
'https://amzn.to/3SknkXf',
'https://amzn.to/3SkqA4V',
'https://amzn.to/3SkwnaO',
'https://amzn.to/3TAosap',
'https://amzn.to/3TBf0U6',
'https://amzn.to/3TbFNGS',
'https://amzn.to/3TBwQ9y',
'https://amzn.to/3TCKGIG',
'https://amzn.to/3TdZHkL',
'https://amzn.to/3TdZpub',
'https://amzn.to/3TEhKQV',
'https://amzn.to/3TfbfnJ',
'https://amzn.to/3TFtK4j',
'https://amzn.to/3Tgkcx4',
'https://amzn.to/3Tkx9pw',
'https://amzn.to/3TS9xsc',
'https://amzn.to/3TSunaU',
'https://amzn.to/3TuSIDw',
'https://amzn.to/3Tv1JwY',
'https://amzn.to/3tV4ywc',
'https://amzn.to/3Tvuzxj',
'https://amzn.to/3tWgr4I',
'https://amzn.to/3TwqxnK',
'https://amzn.to/3TxMzX7',
'https://amzn.to/3TyrSud',
'https://amzn.to/3TzBIMx',
'https://amzn.to/3TzV2Jz',
'https://amzn.to/3TzyWH7',
'https://amzn.to/3U0OdAE',
'https://amzn.to/3V5gpUc',
'https://amzn.to/3VE6429',
'https://amzn.to/3VJlNwQ',
'https://amzn.to/3VkdI0D',
'https://amzn.to/3Vl4ukN',
'https://amzn.to/3VmUx6t',
'https://amzn.to/3Xsrgch',
'https://amzn.to/3yQDv88',
'https://amzn.to/3yU7Y56',
'https://amzn.to/3yUGV9Q',
'https://amzn.to/3zaJrch',
'https://click.dji.com/ALptuYfpN08eQgzSf0T_aA?pm=link',
'https://criaturasinfinitas.com/pages/tienda-onine_-juego-de-cosntruccion_-criaturas-infinitas',
'https://docs.google.com/document/d/1mGcK-QQZ22y2Wngdyc9ABnG175ux-P9Dvyvxvj_rMTw/edit',
'https://docs.google.com/document/d/1mGcK-QQZ22y2Wngdyc9ABnG175ux-P9Dvyvxvj_rMTw/edit',
'https://docs.google.com/document/d/1mGcK-QQZ22y2Wngdyc9ABnG175ux-P9Dvyvxvj_rMTw/edit',
'https://dovetailworkwear.com/collections/overalls-for-women/products/freshley-overalls-in-wabash-stripe?variant=39696700669986',
'https://fallingwatermuseumstore.org/products/the-atom-brick-fallingwater',
'https://github.com/cecio/USBvalve',
'https://glock43xsupply.us/product/glock-43x-for-sale/',
'https://grahamcalferdesigns.etsy.com',
'https://hydro-dipper.com',
'https://intrism.com/products/level-one',
'https://inventorschasm.krtra.com/t/ExP9VOyT0KCp?utm_source=inhouse&utm_medium=hgg&utm_campaign=web&utm_content=makehggsponsor',
'https://inventr.io/step/discount/?utm_source=inhouse&utm_medium=hgg&utm_campaign=web&utm_content=makehggsponsor',
'https://kinggubby.com/collections/bricks-collection',
'https://makerbud.net/',
'https://nexa3d.com/3d-printers/xip/',
'https://shrsl.com/3r61v',
'https://shrsl.com/3r62a',
'https://shrsl.com/3r62d',
'https://shrsl.com/3r62k',
'https://shrsl.com/3rfn4',
'https://shrsl.com/3rfnm',
'https://shrsl.com/3rfns',
'https://shrsl.com/3rfpf',
'https://shrsl.com/3rfpk',
'https://shrsl.com/3rfpt',
'https://shrsl.com/3rfqm',
'https://shrsl.com/3rfqy',
'https://shrsl.com/3rfr6',
'https://shrsl.com/3rfr8',
'https://shrsl.com/3rfra',
'https://shrsl.com/3rfti',
'https://shrsl.com/3rftk',
'https://shrsl.com/3rftl',
'https://shrsl.com/3rftm',
'https://shrsl.com/3rftn',
'https://shrsl.com/3rfto',
'https://shrsl.com/3rfts',
'https://shrsl.com/3rftu',
'https://shrsl.com/3rftv',
'https://shrsl.com/3rhrt',
'https://shrsl.com/3ubn3',
'https://shrsl.com/3uczo',
'https://shrsl.com/3uczr',
'https://shrsl.com/3uczu',
'https://shrsl.com/3uczw',
'https://shrsl.com/3uczz',
'https://shrsl.com/3ud04',
'https://shrsl.com/3ud07',
'https://smartpackindia.biz/',
'https://tamagotchi.com/',
'https://www.alpenglowindustries.com/store/p23/krampus.html#/',
'https://www.alpenglowindustries.com/store/p39/It%27s_Solder_Weather_Series_Bundle.html',
'https://www.alpenglowindustries.com/store/p40/SMT_Garden.html',
'https://www.amazon.com/',
'https://www.amazon.com/Little-Chefs-First-100-Words/dp/0593482662',
'https://www.aviateaudio.com',
'https://www.carhartt.com/product/102482/womens-force-fitted-midweight-utility-legging?categoryCode=default&colorCode=I26_SW',
'https://www.crowdsupply.com/hackerbci/pieeg',
'https://www.donektools.com/?utm_source=inhouse&utm_medium=hgg&utm_campaign=web&utm_content=makehggsponsor',
'https://www.elecrow.com/electrolab.html',
'https://www.instagram.com/dawood_here/',
'https://www.kickstarter.com/projects/livegrid/livegrid',
'https://www.linkedin.com/in/yvonne-chen-578222194/',
'https://www.makershed.com/collections/halloween/products/led-maker-sugar-skull-kit',
'https://www.makershed.com/collections/make-music/products/diy-theremin',
'https://www.makershed.com/products/adafruit-clue',
'https://www.makershed.com/products/make-arduino-electronics-starter-pack',
'https://www.makershed.com/products/make-calculus-print?_pos=3&_sid=37d5459c6&_ss=r',
'https://www.makershed.com/products/make-electronics-3rd-edition-pdf?_pos=6&_sid=2be951793&_ss=r',
'https://www.makershed.com/products/make-geometry?_pos=1&_sid=37d5459c6&_ss=r',
'https://www.makershed.com/products/make-magazine-volume-77-print',
'https://www.makershed.com/products/make-minecraft-for-makers',
'https://www.makershed.com/products/make-origami-paper-circuits-kit',
'https://www.makershed.com/products/make-props-and-costume-armor',
'https://www.makershed.com/products/maker-camp-crafty-cutter',
'https://www.makershed.com/products/makers-notebook-gift-boxed-hardcover-3rd-edition',
'https://www.makershed.com/products/makeybit',
'https://www.makershed.com/products/making-simple-robots-starter-pack',
'https://www.makershed.com/products/rainbow-light-show',
'https://www.makershed.com/products/raspberry-pi-pico-board',
'https://www.makershed.com/products/wio-terminal',
'https://www.mariothemagician.com/product-page/maker-pennant-tote',
'https://www.matterhackers.com/store/l/3doodler-start-essentials-3d-printing-pen-set-blue-pen/sk/MAG77K5U?aff=7533',
'https://www.matterhackers.com/store/l/basf-ultrafuse-316l-metal-composite-3d-printing-filament-175mm/sk/MRDKJRRS?aff=7533',
'https://www.matterhackers.com/store/l/inventables-x-carve-1000/sk/MMY5K70W?aff=7533',
'https://www.matterhackers.com/store/l/inventables-x-carve-pro-cnc-router/sk/MNH5WT8X?aff=7533',
'https://www.matterhackers.com/store/l/ldo-motors-voron-01-3d-printer-kit/sk/MT4H56ZN?aff=7533',
'https://www.matterhackers.com/store/l/mh-build-series-irritant-free-resin-lcddlp/sk/MMYXMGSM?aff=7533',
'https://www.matterhackers.com/store/l/modix-big-60-v3-3d-printer-kit/sk/MUACLF7P?aff=7533',
'https://www.matterhackers.com/store/l/nylonx-carbon-fiber-nylon-filament-1.75mm/sk/MD5LDGS7?aff=7533',
'https://www.matterhackers.com/store/l/peopoly-phenom-prime-msla-3d-printer/sk/MLKKE4MW?aff=7533',
'https://www.matterhackers.com/store/l/printlab-online-3d-printing-curriculum-and-certification-course-teacher-license/sk/MCL0N2SR?aff=7533',
'https://www.matterhackers.com/store/l/pro-series-abs/sk/MX51D4G0?aff=7533',
'https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetson-nano/education-projects/?ncid=em-prom-390237#cid=em06_em-prom_en-us?utm_source=inhouse&utm_medium=hgg&utm_campaign=web&utm_content=makehggsponsor',
'https://www.reinventedmagazine.com/magazine-subscriptions-1',
'Https://www.RockyAir.ca',
'https://www.shareasale.com/m-pr.cfm?productID=1209909917&userID=3405484&merchantID=40843',
'https://www.shareasale.com/m-pr.cfm?productID=1236750483&userID=3405484&merchantID=89076',
'https://www.shareasale.com/m-pr.cfm?productID=1236750959&userID=3405484&merchantID=89076',
'https://www.shareasale.com/m-pr.cfm?productID=1236750993&userID=3405484&merchantID=89076',
'https://www.shareasale.com/m-pr.cfm?productID=1240160418&userID=3405484&merchantID=104276',
'https://www.shareasale.com/m-pr.cfm?productID=1240160421&userID=3405484&merchantID=104276',
'https://www.shareasale.com/m-pr.cfm?productID=1240160426&userID=3405484&merchantID=104276',
'https://www.shareasale.com/m-pr.cfm?productID=1240160428&userID=3405484&merchantID=104276',
'https://www.shareasale.com/m-pr.cfm?productID=1240160429&userID=3405484&merchantID=104276',
'https://www.shareasale.com/m-pr.cfm?productID=1255823264&userID=3405484&merchantID=30103',
'https://www.shareasale.com/m-pr.cfm?productID=1255826221&userID=3405484&merchantID=30103',
'https://www.shareasale.com/m-pr.cfm?productID=1256284338&userID=3405484&merchantID=95592',
'https://www.shareasale.com/m-pr.cfm?productID=1256963505&userID=3405484&merchantID=95592',
'https://www.shareasale.com/m-pr.cfm?productID=1257460108&userID=3405484&merchantID=30103',
'https://www.shareasale.com/m-pr.cfm?productID=1258024310&userID=3405484&merchantID=30103',
'https://www.shareasale.com/m-pr.cfm?productID=1258403724&userID=3405484&merchantID=95592',
'https://www.shareasale.com/m-pr.cfm?productID=783122211&userID=3405484&merchantID=23546',
'https://www.shareasale.com/m-pr.cfm?productID=821195136&userID=3405484&merchantID=23546',
'https://www.shareasale.com/m-pr.cfm?productID=821195138&userID=3405484&merchantID=23546',
'https://www.shareasale.com/m-pr.cfm?productID=821195145&userID=3405484&merchantID=23546',
'https://www.shareasale.com/m-pr.cfm?productID=905413342&userID=3405484&merchantID=23546',
'https://www.shareasale.com/m-pr.cfm?productID=905413344&userID=3405484&merchantID=23546',
'https://www.shareasale.com/m-pr.cfm?productID=905413345&userID=3405484&merchantID=23546',
'https://www.shareasale.com/m-pr.cfm?productID=925852168&userID=3405484&merchantID=89076',
'https://www.shareasale.com/m-pr.cfm?productID=932844198&userID=3405484&merchantID=23546',
'https://www.stirlingkit.com/collections/brand-teching-diy-all-metal-model/products/teching-v8-mechanical-metal-assembly-diy-car-engine-model-kit-500-%20pcs-educational-experiment-toy?utm_source=makezine&utm_medium=pr',
'https://www.stirlingkit.com/products/toyan-v8-nitro-engine-fs-v800-rc-engine-model-building-kits-28cc',
'https://www.tindie.com/products/lixielabs/sensory-bridge-an-advanced-led-music-visualizer/',
'https://www.tindie.com/products/nicola_cimmino/plc14500-nano-1-bit-single-board-computer-kit/',
'https://www.vevor.com/propane-gas-forge-c_11133/vevor-gas-propane-forge-furnace-burner-portable-single-burner-metal-tool-making-p_010466204748',
'https://www.vevor.com/screen-printing-machine-c_11154/4-color-1-station-screen-printing-machine-diy-t-shirt-press-printer-p_010187636447',
'https://www.wildfang.com/products/the-essential-denim-coverall'
];

foreach ($urls as $url) {
    $ch = curl_init($url);

    curl_setopt_array($ch, [
        CURLOPT_NOBODY => true,              // only request headers
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_FOLLOWLOCATION => true,      // follow redirects
        CURLOPT_MAXREDIRS => 10,             // limit redirect depth
        CURLOPT_TIMEOUT => 10,               // avoid hanging
    ]);

    curl_exec($ch);
    $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    $finalUrl = curl_getinfo($ch, CURLINFO_EFFECTIVE_URL);
    $error = curl_error($ch);

    curl_close($ch);

    if ($error) {
        echo "❌ $url — cURL error: $error<br />";
    } elseif ($httpCode >= 400 || $httpCode == 0) {
        echo "❌ $url — HTTP $httpCode (Broken)<br />";
        if ($finalUrl && $finalUrl !== $url) {
            echo "   ↳ Redirected to: $finalUrl<br />";
        }
    } else {
        echo "✅ $url — HTTP $httpCode (OK)<br />";
        if ($finalUrl && $finalUrl !== $url) {
            echo "   ↳ Final URL: $finalUrl<br />";
        }
    }

    echo "\n";
}
?>
