<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_62c797b94ad2e',
		'title' => 'Select Map Locations',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_617170da43b98',
				'label' => 'Map Locations',
				'name' => 'mapify_map_location_selector',
				'type' => 'mapify_map_locations_relationship',
				'instructions' => 'Select map locations to show on this map.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
					1 => 'post_type',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),		
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_604992a03594f',
		'title' => 'Basic Settings',
		'fields' => array(			
			array(
				'key' => 'mapify_acf_field_604992b7bb672',
				'label' => 'Mapify Map Status',
				'name' => 'mapify_map_status',
				'type' => 'mapify_map_status',
				'instructions' => 'The image mode will works only if you already have uploaded the custom Maptiles image.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'mapify_acf_field_62317cf84bac5',
				'label' => 'Routes',
				'name' => 'mapify_map_routes_selector',
				'type' => 'relationship',
				'instructions' => 'Select map routes to show on this map.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'route',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),
			array(
				'key' => 'mapify_acf_field_611b2bff7cd49',
				'label' => 'Map Area',
				'name' => 'mapify_map_area_selector',
				'type' => 'relationship',
				'instructions' => 'Select map areas to show on this map. Your selected areas will be visible on the map perview after saved.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'map-drawer',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'id',
			),			
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));

	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_611b2bec9935b',
		'title' => 'Look and Feel',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_6066c1bda5cca',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_6049c08205a9c',
				'label' => 'Default Pin Image',
				'name' => 'mapify_default_pin_image',
				'type' => 'mapify_pin_uploader',
				'instructions' => 'This image will serve as a default pinpoint for your Map. 
			PNG file with transparent background is suggested (supports jpg, gif, png). 
			You can override this by editing the individual Map Location pinpoints.<br>
			<b>When using .svg make sure it has it\'s width and height xml attributes set.</b>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'mapify_acf_field_6066c116a5cc7',
				'label' => 'Hide Locations by default',
				'name' => '_map_pins_hide_initially',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6049c0c905a9d',
				'label' => 'Enable Mouse Zoom',
				'name' => '_map_enable_zoom',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6049c10105a9e',
				'label' => 'Enable Manual Zoom',
				'name' => '_map_enable_zoom_manual',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6066c132a5cc8',
				'label' => 'Enable Clustering',
				'name' => '_map_enable_clustering',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6066c152a5cc9',
				'label' => 'Enable "Use My Location"',
				'name' => '_map_enable_use_my_location',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_63f2f0bc21732',
				'label' => 'Address Format',
				'name' => '_map_address_format',
				'type' => 'text',
				'instructions' => 'Available address tags: <code>[phone]</code> <code>[address_line_1]</code> <code>[address_line_2]</code> <code>[city]</code> <code>[state]</code> <code>[zip]</code> <code>[country]</code><br>Add <code>[br]</code> tag for a new line.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '[address_line_1] [br][address_line_2] [br][city] [state] [zip] [br][country] [br][phone]',
				'placeholder' => '[address_line_1] [br][address_line_2] [br][city] [state] [zip] [br][country] [br][phone]',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_6066c1d4a5ccb',
				'label' => 'Popup Text / Labels',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_6066c1eba5ccc',
				'label' => 'Directions Button',
				'name' => '_map_label_directions_button',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Get Directions',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_6066c1fda5ccd',
				'label' => 'Location Details',
				'name' => '_map_label_location_details',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Location Details',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_6064373d6554a',
		'title' => 'Search & Filter Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_60643af5696ea',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_60643765dd45c',
				'label' => 'Enable Search',
				'name' => '_map_enable_search',
				'type' => 'select',
				'instructions' => 'Works on map mode only',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6064381edd45d',
				'label' => 'Enable Filter Dropdown',
				'name' => '_map_enable_filters',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643845dd45e',
				'label' => 'Enable Filter List',
				'name' => '_map_enable_filters_list',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643875dd45f',
				'label' => 'Center Map on Search Results',
				'name' => '_map_search_center',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643888dd460',
				'label' => 'Center Map on Filters',
				'name' => '_map_filters_center',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643a1f4182d',
				'label' => 'Text / Labels Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_60643b528a175',
				'label' => 'Filter Dropdown',
				'name' => '_map_label_filter_dropdown',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Default View',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643b6b8a176',
				'label' => 'Filter List',
				'name' => '_map_label_filter_list',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Default View',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643b888a177',
				'label' => 'First Label Search',
				'name' => '_map_label_search',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Enter location..',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_6204535575945',
				'label' => 'Second Label Search',
				'name' => '_map_label_search_second',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '..or enter a name!',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643ba08a178',
				'label' => 'Search Within',
				'name' => '_map_label_search_within',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Within',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_61c29f3230cd1',
				'label' => 'Search Any Within',
				'name' => '_map_label_search_any_within',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Any Within',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_61c29f3630cd2',
				'label' => 'Search All Within',
				'name' => '_map_label_search_all_within',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'All Within',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_60baef30f9f2b',
				'label' => 'No Search Results',
				'name' => '_map_label_no_search_results',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'mapify_acf_field_60baef63f9f2c',
						'label' => 'Line 1',
						'name' => 'line_1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'No locations were found.',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'mapify_acf_field_60baef75f9f2d',
						'label' => 'Line 2',
						'name' => 'line_2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Please search again.',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'mapify_acf_field_60baf00143efa',
				'label' => 'No Search Results With Closest Location',
				'name' => '_map_label_no_search_results_with_closest',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'mapify_acf_field_60baf03c43efb',
						'label' => 'Line 1',
						'name' => 'line_1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'No locations were found within your search criteria. Please search again.',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'mapify_acf_field_60baf05f43efc',
						'label' => 'Line 2',
						'name' => 'line_2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Or ...',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'mapify_acf_field_60baf06e43efd',
						'label' => 'Line 3',
						'name' => 'line_3',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'See the Closest Location',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'mapify_acf_field_60baf08243efe',
				'label' => 'Search Geolocation Failure',
				'name' => '_map_label_search_geolocation_failure',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'row',
				'sub_fields' => array(
					array(
						'key' => 'mapify_acf_field_60baf08243eff',
						'label' => 'Line 1',
						'name' => 'line_1',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Could not find the entered address.',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'mapify_acf_field_60baf08243f00',
						'label' => 'Line 2',
						'name' => 'line_2',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => 'Please check your spelling and try again.',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 3,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_60643e770d24c',
		'title' => 'Search Radius Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_60643e7abf1b3',
				'label' => 'Default	Search Radius',
				'name' => '_map_search_radius',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 50,
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643f9fbf1b4',
				'label' => 'Search Radius Unit',
				'name' => '_map_search_radius_unit',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'mi' => 'Miles',
					'km' => 'Kilometers',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643fd6bf1b5',
				'label' => 'Search Region Bias',
				'name' => '_map_search_region_bias',
				'type' => 'text',
				'instructions' => 'Optional. Used to help choose between similarly named locations in different countries. Use a 2-letter ISO 3166-1 country code e.g. GB instead of United Kingdom. More than one country code can be used by adding a comma such as US,GB (without spaces).',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_60643ffebf1b6',
				'label' => 'Enable Front-End Search Radius',
				'name' => '_map_enable_search_radius',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => 'yes',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60644059bf1b7',
				'label' => 'Front-End Search Radius Options',
				'name' => 'mapify_front_end_search_radius_options',
				'type' => 'mapify_repeater',
				'instructions' => 'Leave blank for default values: 5, 10, 25, 50, 100, 500.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Option',
				'sub_fields' => array(
					array(
						'key' => 'mapify_acf_field_60644097bf1b8',
						'label' => 'Distance',
						'name' => 'distance',
						'type' => 'number',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'min' => '',
						'max' => '',
						'step' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 4,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_6049c219a07ff',
		'title' => 'Tooltip & Marker / Pinpoint Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_6049c22201c80',
				'label' => 'Animated Tooltips',
				'name' => '_map_animate_tooltips',
				'type' => 'select',
				'instructions' => 'Add a subtle animation to the tooltip that appears when hovering on a location.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6066c3bb20ec0',
				'label' => 'Tooltip Image Orientation',
				'name' => '_map_tooltip_image_orientation',
				'type' => 'select',
				'instructions' => 'Specify placement of the thumbnail image on the left or top of the text in the tooltip (must upload a "featured image" in sidebar).',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'left' => 'Left (recommended)',
					'top' => 'Top',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6049c2af01c81',
				'label' => 'Animated Pinpoints',
				'name' => '_map_animate_pinpoints',
				'type' => 'select',
				'instructions' => 'Add a subtle animation to the pinpoints as they populate the map.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_606699eea5f4e',
		'title' => 'Interactive List of Locations Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_60669b0497af1',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_60669a0b97aee',
				'label' => 'Enable',
				'name' => '_map_mll_include',
				'type' => 'select',
				'instructions' => 'Adds locations below the map in an organized, interactive list.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'n' => 'No',
					'y' => 'Yes',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60669a7797aef',
				'label' => 'Number of locations in list',
				'name' => '_map_mll_number_of_locations',
				'type' => 'number',
				'instructions' => 'Specify how many locations appear in list before pagination.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '3',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array(
				'key' => 'mapify_acf_field_60669aa497af0',
				'label' => 'Hide list by default',
				'name' => '_map_mll_hide_in_default_view',
				'type' => 'select',
				'instructions' => 'Only the relevant results display in the list beneath the map after a search is performed, or a filter is selected.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'no' => 'No',
					'yes' => 'Yes',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_60669b1997af2',
				'label' => 'Buttons Labels',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_60669b7c2ec14',
				'label' => 'Open Pop-up Button Label',
				'name' => '_map_label_interactive_list_open_popup_button',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'More Details',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_60669b942ec15',
				'label' => 'Directions Button Label',
				'name' => '_map_label_interactive_list_directions_button',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'Get Directions',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_60669bb12ec16',
				'label' => 'Buttons Colors',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_60669bd1aa4e2',
				'label' => 'Open Pop-up Button Background',
				'name' => '_map_label_interactive_list_open_popup_bgcolor',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#61849c',
			),
			array(
				'key' => 'mapify_acf_field_60669c04aa4e3',
				'label' => 'Open Pop-up Button Text Color',
				'name' => '_map_label_interactive_list_open_popup_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#ffffff',
			),
			array(
				'key' => 'mapify_acf_field_60669c26aa4e4',
				'label' => 'Directions Button Background',
				'name' => '_map_label_interactive_list_directions_bgcolor',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#d2845b',
			),
			array(
				'key' => 'mapify_acf_field_60669c4baa4e5',
				'label' => 'Directions Button Text Color',
				'name' => '_map_label_interactive_list_directions_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#ffffff',
			),
			array(
				'key' => 'mapify_acf_field_60669c66aa4e6',
				'label' => 'Buttons Hover Background Color',
				'name' => '_map_label_interactive_list_buttons_hover_bgcolor',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#ffffff',
			),
			array(
				'key' => 'mapify_acf_field_60669c83aa4e7',
				'label' => 'Buttons Hover Text Color',
				'name' => '_map_label_interactive_list_buttons_hover_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#000000',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 6,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_60669ea553670',
		'title' => 'Color / Design Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_60669ebe7c340',
				'label' => 'Map Background',
				'name' => '_map_background_color',
				'type' => 'color_picker',
				'instructions' => 'Works on image mode only',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			array(
				'key' => 'mapify_acf_field_60669f1a7c341',
				'label' => 'Tooltip Background',
				'name' => '_map_tooltip_background_color',
				'type' => 'color_picker',
				'instructions' => 'Works on image mode only',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#FFFFFF',
			),
			array(
				'key' => 'mapify_acf_field_60669f417c342',
				'label' => 'Tooltip Transparency',
				'name' => '_map_tooltip_background_transparency',
				'type' => 'number',
				'instructions' => 'The value is a percentage',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '100',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 0,
				'max' => 100,
				'step' => '',
			),
			array(
				'key' => 'mapify_acf_field_60669f9ca031e',
				'label' => 'Tooltip Text Color',
				'name' => '_map_tooltip_text_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#525252',
			),
			array(
				'key' => 'mapify_acf_field_60669fcca031f',
				'label' => 'Popup Background',
				'name' => '_map_popup_background_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#FFFFFF',
			),
			array(
				'key' => 'mapify_acf_field_6066a004a0320',
				'label' => 'Popup Header',
				'name' => '_map_popup_header_background_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#F7F7F7',
			),
			array(
				'key' => 'mapify_acf_field_6066a03ca0321',
				'label' => 'Popup Date Background',
				'name' => '_map_popup_date_background_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#566069',
			),
			array(
				'key' => 'mapify_acf_field_6066a05aa0322',
				'label' => 'Popup Accent',
				'name' => '_map_popup_accent_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#2ED2E1',
			),
			array(
				'key' => 'mapify_acf_field_61fccd0bcf3fd',
				'label' => 'Location Circle Color',
				'name' => '_map_location_circle_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#3388ff',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 7,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_6066bc3dd3999',
		'title' => 'Map Theme',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_6066bc5989e35',
				'label' => 'Map Style',
				'name' => '_map_google_mode',
				'type' => 'select',
				'instructions' => 'Select you map style',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => MAPIFY_MAP_STYLES,
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 8,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_6049938682e7f',
		'title' => 'Image Map Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_6049939b7729c',
				'label' => 'Mapify Map Tiles Uploader',
				'name' => 'mapify_map_tiles_uploader',
				'type' => 'mapify_map_tiles_uploader',
				'instructions' => 'You must save this map settings first, before the image can be processed to support multiple zoom levels.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'uploads-folder-name' => 'mpfy',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 9,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_604993ff7ee86',
		'title' => 'Default Zoom Level and Location Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_60499406a9c44',
				'label' => 'Mapify Map Selector',
				'name' => 'mapify_map_selector',
				'type' => 'mapify_map_selector',
				'instructions' => 'Use this map to preview the style, and to set your default zoom level. You may also drag and drop center location as needed.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'lattitude' => ACF_MAPIFYPRO_DEFAULT_LAT,
				'longitude' => ACF_MAPIFYPRO_DEFAULT_LNG,
				'zoom_level' => ACF_MAPIFYPRO_DEFAULT_ZOOM,
				'map_selector' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
endif;