<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'mapify_acf_group_611f428c83a17',
		'title' => 'Map Area Drawer',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_611f42ae548a7',
				'label' => 'Map Canvas',
				'name' => 'map_drawer_canvas',
				'type' => 'mapify_map_drawer',
				'instructions' => 'Select a location on the map.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'lattitude' => ACF_MAPIFYPRO_DEFAULT_LAT,
				'longitude' => ACF_MAPIFYPRO_DEFAULT_LNG,
				'zoom_level' => ACF_MAPIFYPRO_DEFAULT_ZOOM,
			),
			array(
				'key' => 'mapify_acf_field_612085587ced1',
				'label' => '',
				'name' => '',
				'type' => 'message',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '<div style="font-weight: 500;font-size: 16px;margin: -12px 0 0;">Below settings will be applied after you save (publish) or update this map area.</div>',
				'new_lines' => 'wpautop',
				'esc_html' => 0,
			),
			array(
				'key' => 'mapify_acf_field_612077b484e62',
				'label' => 'Border Color',
				'name' => 'map_drawer_border_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#1e73be',
			),
			array(
				'key' => 'mapify_acf_field_612077dc84e63',
				'label' => 'Area Fill Color',
				'name' => 'map_drawer_fill_color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#1e73be',
			),
			array(
				'key' => 'mapify_acf_field_612ef5caa7e87',
				'label' => 'Area Fill Opacity',
				'name' => 'map_drawer_fill_opacity_percentage',
				'type' => 'range',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => 40,
				'min' => '0',
				'max' => '100',
				'step' => '1',
				'prepend' => '',
				'append' => '%',
			),
			array(
				'key' => 'mapify_acf_field_612077f684e64',
				'label' => 'Image',
				'name' => 'map_drawer_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'array',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'mapify_acf_field_6120780d84e65',
				'label' => 'Description',
				'name' => 'map_drawer_description',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map-drawer',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	));
	
endif;