<?php

if( function_exists('acf_add_local_field_group') ):

	$mapify_acf_group_62c79b2459423 = array(
		'key' => 'mapify_acf_group_62c79b2459423',
		'title' => 'Select Maps',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_604d81bbc44d5',
				'label' => 'Maps',
				'name' => 'mapify_location_maps',
				'type' => 'relationship',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'post_type' => array(
					0 => 'map',
				),
				'taxonomy' => '',
				'filters' => array(
					0 => 'search',
				),
				'elements' => '',
				'min' => '',
				'max' => '',
				'return_format' => 'object',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map-location',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	);

	$mapify_acf_group_604cde8eca652 = array(
		'key' => 'mapify_acf_group_604cde8eca652',
		'title' => 'MapifyPro Options',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_606acf667c86f',
				'label' => 'General Settings',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_604cdf0453143',
				'label' => 'Enable Popup',
				'name' => '_map_location_tooltip_enabled',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_606acb39aa426',
				'label' => 'Take visitor to another page on clicking location?',
				'name' => '_map_location_external_url_enable',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => 'no',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_606acb65aa427',
				'label' => 'Enter URL',
				'name' => '_map_location_external_url_url',
				'type' => 'text',
				'instructions' => 'This will override the pop-up and take the visitor to a new page when they click on the location marker.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606acb93aa428',
				'label' => 'Open in',
				'name' => '_map_location_external_url_target',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'_blank' => 'New Window',
					'_self' => 'Current Window',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_604cdf5053144',
				'label' => 'Enable Tooltip',
				'name' => '_map_location_tooltip_show',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_604cdfb374849',
				'label' => 'Close Tooltip',
				'name' => '_map_location_tooltip_close',
				'type' => 'select',
				'instructions' => '<b>Automatically</b>: This will cause the tooltip to automatically hide when the user hovers off the location.<br><b>Manually</b>: Good if you want to add links to the tooltip.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'auto' => 'Automatically',
					'manual' => 'Manually',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_606acbf9aa429',
				'label' => 'Include Location Information',
				'name' => '_map_location_popup_location_information',
				'type' => 'select',
				'instructions' => 'Shows or hides the location information in the location popup.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_606acc23aa42b',
				'label' => 'Include Directions',
				'name' => '_map_location_popup_directions',
				'type' => 'select',
				'instructions' => 'Shows or hides the directions button in the location popup.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_604ce035e7d8e',
				'label' => 'Tooltip',
				'name' => '_map_location_tooltip',
				'type' => 'textarea',
				'instructions' => 'This is the brief text that appears in the tooltip when a user hovers over this location. You may use basic html text formatting, such as &lt;br&gt;, &lt;i&gt;, etc. Use the [directions] shortcode to add a Get Directions button.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'mapify_acf_field_606acc63aa42c',
				'label' => 'Include on Selected Map(s) Location List?',
				'name' => '_map_location_mll_include',
				'type' => 'select',
				'instructions' => 'Shows or hides the directions button in the location popup.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'yes' => 'Yes',
					'no' => 'No',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_606acd19aa42d',
				'label' => 'Short Description',
				'name' => '_map_location_mll_description',
				'type' => 'textarea',
				'instructions' => 'Short description of the location that appears in the Interactive List. Note that this is independent of the tooltip and main description area that appears in the pop-up.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'mapify_acf_field_606aced95589f',
				'label' => 'Pin Image',
				'name' => 'mapify_pin_image',
				'type' => 'mapify_pin_uploader',
				'instructions' => 'This image will serve as a default pinpoint for your Map. 
			PNG file with transparent background is suggested (supports jpg, gif, png). 
			You can override this by editing the individual Map Location pinpoints.<br>
			<b>When using .svg make sure it has it\'s width and height xml attributes set.</b>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'mapify_acf_field_606ad0017c870',
				'label' => 'Address Details',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_606ad0177c871',
				'label' => 'Phone',
				'name' => '_map_location_phone',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad0267c872',
				'label' => 'Address Line 1',
				'name' => '_map_location_address',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad0367c873',
				'label' => 'Address Line 2',
				'name' => '_map_location_address_2',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad0567c874',
				'label' => 'City',
				'name' => '_map_location_city',
				'type' => 'text',
				'instructions' => 'Used for location search in image mode.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad0797c875',
				'label' => 'State',
				'name' => '_map_location_state',
				'type' => 'text',
				'instructions' => 'Used for location search in image mode.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad0907c876',
				'label' => 'Zip',
				'name' => '_map_location_zip',
				'type' => 'text',
				'instructions' => 'Used for location search in image mode.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad0ba7c877',
				'label' => 'Country',
				'name' => '_map_location_country',
				'type' => 'text',
				'instructions' => 'Used for location search in image mode.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad0d97c878',
				'label' => 'Directions URL',
				'name' => '_map_location_directions_url',
				'type' => 'text',
				'instructions' => 'Allows you to specify a directions url to use for all directions links. Leave blank to use the geocoordinates instead (default). <a href="https://mapifypro.zendesk.com/hc/en-us/articles/229649228-How-do-I-Force-Directions-to-a-Specific-Address" target="_blank">More Info Here</a>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'mapify_acf_field_606ad1187c879',
				'label' => 'Links',
				'name' => '_map_location_links',
				'type' => 'mapify_repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'block',
				'button_label' => 'Add Entry',
				'sub_fields' => array(
					array(
						'key' => 'mapify_acf_field_606ad1ae7c87a',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'mapify_acf_field_606ad1bb7c87b',
						'label' => 'Text',
						'name' => 'text',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'mapify_acf_field_606ad1c27c87c',
						'label' => 'Open in New Window',
						'name' => 'open_in_new_window',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							'_top' => 'No',
							'_blank' => 'Yes',
						),
						'default_value' => false,
						'allow_null' => 0,
						'multiple' => 0,
						'ui' => 0,
						'return_format' => 'value',
						'ajax' => 0,
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'mapify_acf_field_606ad261a486f',
				'label' => 'Share Buttons',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_60706d50ff732',
				'label' => 'Share Services',
				'name' => '_map_location_share',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'facebook' => 'Facebook',
					'pinterest' => 'Pinterest',
					'twitter' => 'Twitter',
					'linkedin' => 'LinkedIn',
					'whatsapp' => 'WhatsApp',
					'email' => 'Email',
				),
				'allow_custom' => 0,
				'default_value' => array(
				),
				'layout' => 'vertical',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'mapify_acf_field_6142e954bd8c5',
				'label' => 'Google Rich Results',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'mapify_acf_field_614310b2d0d8a',
				'label' => 'Enable Google Rich Results',
				'name' => 'mapify_grs_enable',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'Enabled',
				'ui_off_text' => 'Disabled',
			),
			array(
				'key' => 'mapify_acf_field_6142ed8adb5ee',
				'label' => 'Location Type',
				'name' => 'mapify_grs_location_type',
				'type' => 'select',
				'instructions' => 'Enter Location Type to enable this to be listed as a Google Rich Result.',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'mapify_acf_field_614310b2d0d8a',
							'operator' => '==',
							'value' => '1',
						),
					),
				),
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'AnimalShelter' => 'Animal Shelter',
					'ArchiveOrganization' => 'Archive Organization',
					'AutomotiveBusiness' => 'Automotive Business',
					'AutoBodyShop' => 'Auto Body Shop',
					'AutoDealer' => 'Auto Dealer',
					'AutoPartsStore' => 'Auto Parts Store',
					'AutoRental' => 'Auto Rental',
					'AutoRepair' => 'Auto Repair',
					'AutoWash' => 'Auto Wash',
					'GasStation' => 'Gas Station',
					'MotorcycleDealer' => 'Motorcycle Dealer',
					'MotorcycleRepair' => 'Motorcycle Repair',
					'ChildCare' => 'Child Care',
					'Dentist' => 'Dentist',
					'DryCleaningOrLaundry' => 'Dry Cleaning Or Laundry',
					'EmergencyService' => 'Emergency Service',
					'FireStation' => 'Fire Station',
					'Hospital' => 'Hospital',
					'PoliceStation' => 'Police Station',
					'EmploymentAgency' => 'Employment Agency',
					'EntertainmentBusiness' => 'Entertainment Business',
					'AmusementPark' => 'Amusement Park',
					'ArtGallery' => 'Art Gallery',
					'ComedyClub' => 'Comedy Club',
					'MovieTheater' => 'Movie Theater',
					'FinancialService' => 'Financial Service',
					'AccountingService' => 'Accounting Service',
					'AutomatedTeller' => 'Automated Teller',
					'BankOrCreditUnion' => 'Bank Or Credit Union',
					'InsuranceAgency' => 'Insurance Agency',
					'FoodEstablishment' => 'Food Establishment',
					'Bakery' => 'Bakery',
					'CafeOrCoffeeShop' => 'Cafe Or Coffee Shop',
					'FastFoodRestaurant' => 'Fast Food Restaurant',
					'IceCreamShop' => 'Ice Cream Shop',
					'Restaurant' => 'Restaurant',
					'GovernmentOffice' => 'Government Office',
					'PostOffice' => 'Post Office',
					'HealthAndBeautyBusiness' => 'Health And Beauty Business',
					'BeautySalon' => 'Beauty Salon',
					'DaySpa' => 'Day Spa',
					'HairSalon' => 'Hair Salon',
					'HealthClub' => 'Health Club',
					'NailSalon' => 'NailSalon',
					'HomeAndConstructionBusiness' => 'Home And Construction Business',
					'Electrician' => 'Electrician',
					'GeneralContractor' => 'General Contractor',
					'HVACBusiness' => 'HVAC Business',
					'HousePainter' => 'House Painter',
					'Locksmith' => 'Locksmith',
					'MovingCompany' => 'Moving Company',
					'Plumber' => 'Plumber',
					'RoofingContractor' => 'Roofing Contractor',
					'InternetCafe' => 'Internet Cafe',
					'LegalService' => 'Legal Service',
					'Attorney' => 'Attorney',
					'Notary' => 'Notary',
					'Library' => 'Library',
					'LodgingBusiness' => 'Lodging Business',
					'BedAndBreakfast' => 'Bed And Breakfast',
					'Campground' => 'Campground',
					'Hostel' => 'Hostel',
					'Hotel' => 'Hotel',
					'Motel' => 'Motel',
					'Resort' => 'Resort',
					'MedicalBusiness' => 'Medical Business',
					'CommunityHealth' => 'Community Health',
					'Dermatology' => 'Dermatology',
					'DietNutrition' => 'Diet Nutrition',
					'Emergency' => 'Emergency',
					'Geriatric' => 'Geriatric',
					'Gynecologic' => 'Gynecologic',
					'MedicalClinic' => 'Medical Clinic',
					'Midwifery' => 'Midwifery',
					'Nursing' => 'Nursing',
					'Obstetric' => 'Obstetric',
					'Oncologic' => 'Oncologic',
					'Optician' => 'Optician',
					'Optometric' => 'Optometric',
					'Otolaryngologic' => 'Otolaryngologic',
					'Pediatric' => 'Pediatric',
					'Pharmacy' => 'Pharmacy',
					'Physician' => 'Physician',
					'Physiotherapy' => 'Physiotherapy',
					'PlasticSurgery' => 'Plastic Surgery',
					'Podiatric' => 'Podiatric',
					'PrimaryCare' => 'Primary Care',
					'Psychiatric' => 'Psychiatric',
					'PublicHealth' => 'Public Health',
					'ProfessionalService' => 'Professional Service',
					'RadioStation' => 'Radio Station',
					'RealEstateAgent' => 'Real Estate Agent',
					'RecyclingCenter' => 'Recycling Center',
					'SelfStorage' => 'Self Storage',
					'ShoppingCenter' => 'Shopping Center',
					'SportsActivityLocation' => 'Sports Activity Location',
					'BowlingAlley' => 'Bowling Alley',
					'ExerciseGym' => 'Exercise Gym',
					'GolfCourse' => 'Golf Course',
					'PublicSwimmingPool' => 'Public Swimming Pool',
					'SkiResort' => 'Ski Resort',
					'SportsClude' => 'Sports Clude',
					'StadiumOrArena' => 'Stadium Or Arena',
					'TennisComplex' => 'Tennis Complex',
					'Store' => 'Store',
					'AutoPartsStore' => 'Auto Parts Store',
					'BikeStore' => 'Bike Store',
					'BookStore' => 'Book Store',
					'ClothingStore' => 'Clothing Store',
					'ComputerStore' => 'Computer Store',
					'ConvenienceStore' => 'Convenience Store',
					'DepartmentStore' => 'Department Store',
					'ElectronicStore' => 'Electronic Store',
					'Florist' => 'Florist',
					'FurnitureStore' => 'Furniture Store',
					'GardenStore' => 'Garden Store',
					'GroceryStore' => 'Grocery Store',
					'HardwareStore' => 'Hardware Store',
					'HobbyShop' => 'Hobby Shop',
					'HomeGoodsStore' => 'Home Goods Store',
					'JewleryStore' => 'Jewlery Store',
					'MensClothingStore' => 'Mens Clothing Store',
					'MobilePhoneStore' => 'Mobile Phone Store',
					'MovieRentalStore' => 'Movie Rental Store',
					'MusicStore' => 'Music Store',
					'OfficeEquipmentStore' => 'Office Equipment Store',
					'OutletStore' => 'Outlet Store',
					'PawnShop' => 'Pawn Shop',
					'PetStore' => 'Pet Store',
					'ShoeStore' => 'Shoe Store',
					'SportingGoodsStore' => 'Sporting Goods Store',
					'TireShop' => 'Tire Shop',
					'ToyStore' => 'Toy Store',
					'WhoesaleStore' => 'Whoesale Store',
					'TelevisionStation' => 'Television Station',
					'TouristInformationCenter' => 'Tourist Information Center',
					'TravelAgency' => 'Travel Agency',
					'LocalBusiness' => 'Other',
				),
				'default_value' => false,
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 1,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6142eda2db5ef',
				'label' => 'Site URL',
				'name' => 'mapify_grs_site_url',
				'type' => 'url',
				'instructions' => 'If blank, this will default to the URL of the Map Location.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'mapify_acf_field_6142ee1adb5f0',
				'label' => 'Price Range',
				'name' => 'mapify_grs_price_range',
				'type' => 'text',
				'instructions' => 'The price range of the business, for example $$$.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '$$$',
				'placeholder' => '$$$',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map-location',
				),
				array(
					'param' => 'current_user_role',
					'operator' => '!=',
					'value' => 'mpfy_contributor',
				),
			),
		),
		'menu_order' => 1,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'left',
		'instruction_placement' => 'field',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	);

	$mapify_acf_group_604ce142884e6 = array(
		'key' => 'mapify_acf_group_604ce142884e6',
		'title' => 'MapifyPro Gallery Settings',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_604ce14b0e4b9',
				'label' => 'Video Embed Code',
				'name' => '_map_location_video_embed',
				'type' => 'textarea',
				'instructions' => 'Use YouTube, Vimeo or Facebook iframe embed codes or URL to include a video in your location’s pop-up gallery. If left blank, the gallery will revert to an image gallery only.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'mapify_acf_field_604ce18a0e4ba',
				'label' => 'Gallery Images',
				'name' => 'mapify_gallery_images',
				'type' => 'mapify_gallery_uploader',
				'instructions' => 'Add your desired images from the gallery. You can always edit the image URL after it.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map-location',
				),
			),
		),
		'menu_order' => 2,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	);

	$mapify_acf_group_604ce1e87a9ec = array(
		'key' => 'mapify_acf_group_604ce1e87a9ec',
		'title' => 'MapifyPro Map Location',
		'fields' => array(
			array(
				'key' => 'mapify_acf_field_604ce1f6dab7d',
				'label' => 'Location',
				'name' => 'location',
				'type' => 'mapify_map_locator',
				'instructions' => 'Select a location on the map.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'lattitude' => ACF_MAPIFYPRO_DEFAULT_LAT,
				'longitude' => ACF_MAPIFYPRO_DEFAULT_LNG,
				'zoom_level' => ACF_MAPIFYPRO_DEFAULT_ZOOM,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'map-location',
				),				
			),
		),
		'menu_order' => 3,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
	);

	// maybe include these custom fields to blog-post as map-location
	if ( mpfy_blog_post_is_map_location() ) {
		$mapify_acf_group_62c79b2459423[ 'location' ][] = array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		);
		
		$mapify_acf_group_604cde8eca652[ 'location' ][] = array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		);

		$mapify_acf_group_604ce142884e6[ 'location' ][] = array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		);

		$mapify_acf_group_604ce1e87a9ec[ 'location' ][] = array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		);
	}


	acf_add_local_field_group( $mapify_acf_group_62c79b2459423 );	
	acf_add_local_field_group( $mapify_acf_group_604cde8eca652 );	
	acf_add_local_field_group( $mapify_acf_group_604ce142884e6 );	
	acf_add_local_field_group( $mapify_acf_group_604ce1e87a9ec );
	
endif;