<?php

/**
 * @file  class-gravityview-inline-edit-field-survey.php
 *
 * Adds inline edit support for Gravity Forms Survey Add-On field types:
 * - likert
 * - rank
 * - rating
 *
 * All types are defined in this single file per request.
 *
 * @since 2.7.0
 */

if ( ! class_exists( 'GFForms' ) ) {
	return;
}

/**
 * Survey field: Handles likert, rank, and rating subtypes.
 */
class GravityView_Inline_Edit_Field_Survey extends GravityView_Inline_Edit_Field {

	public $gv_field_name = 'survey';

	public $inline_edit_type = 'survey';

	public $set_value = false;

	public $standard_live_update = false;

	/**
	 * Dynamically set inline type and attributes for Survey subtypes: likert, rank, rating, radio, checkbox, select, text, textarea.
	 */
	public function modify_inline_edit_attributes( $wrapper_attributes, $field_input_type, $field_id, $entry, $current_form, $gf_field ) {
		$subtype = isset( $gf_field->inputType ) ? $gf_field->inputType : ( isset( $gf_field->type ) ? $gf_field->type : 'survey' );

		if ( $subtype === 'likert' ) {
			$value                                    = $this->get_likert_value( $gf_field, $entry, $field_id );
			$wrapper_attributes['data-multiple-rows'] = $gf_field->gsurveyLikertEnableMultipleRows ? '1' : '0';
		} elseif ( $subtype === 'checkbox' ) {
			// Checkbox survey fields work like regular checkboxes - they have multiple inputs
			$value = $this->get_checkbox_value( $gf_field, $entry, $field_id );
		} else {
			// Handle rank, rating, radio, select, text, textarea, and other simple survey field types
			$value = $this->get_simple_field_value( $entry, $field_id );
		}

		// Pass choices to JavaScript for fields that need them (not needed for text/textarea)
		if ( ! in_array( $subtype, array( 'text', 'textarea' ), true ) ) {
			$wrapper_attributes['data-source'] = wp_json_encode( $gf_field->choices );
		}

		$wrapper_attributes['data-value']   = $value;
		$wrapper_attributes['data-subtype'] = $subtype;

		// Pass the HTML template generated by Gravity Forms (without values for the editor)
		parent::add_field_template( $this->inline_edit_type, '<div class="gravity-theme gform-settings__content gform-settings-panel__content">' . $gf_field->get_field_input( $current_form, '', $entry ) . '</div>', $current_form['id'], $field_id );

		return parent::modify_inline_edit_attributes( $wrapper_attributes, $field_input_type, $field_id, $entry, $current_form, $gf_field );
	}

	/**
	 * Get the value used in Inline Edit `data-value` attribute for Likert fields
	 *
	 * @param GF_Field $gf_field Gravity Forms field object
	 * @param array    $entry The entry
	 * @param int      $field_id The field ID
	 *
	 * @return string JSON-encoded value or empty string
	 */
	public function get_likert_value( $gf_field, $entry, $field_id ) {

		if ( $gf_field->gsurveyLikertEnableMultipleRows ) {
			// Multiple rows: gather all sub-inputs
			$values = array();

			if ( is_array( $gf_field->inputs ) ) {
				foreach ( $gf_field->inputs as $input ) {
					$input_id = $input['id'];
					$value    = rgar( $entry, $input_id );

					if ( ! empty( $value ) ) {
						$values[ $input_id ] = $value;
					}
				}
			}

			if ( empty( $values ) ) {
				return '';
			}

			$encoded = wp_json_encode( $values );

			return false !== $encoded ? $encoded : '';
		} else {
			// Single row: just return the main field value
			$value = rgar( $entry, $field_id );
			if ( empty( $value ) ) {
				return '';
			}

			$encoded = wp_json_encode( $value );

			return false !== $encoded ? $encoded : '';
		}
	}

	/**
	 * Get the value used in Inline Edit `data-value` attribute for Checkbox survey fields
	 *
	 * @param GF_Field $gf_field Gravity Forms field object
	 * @param array    $entry The entry
	 * @param int      $field_id The field ID
	 *
	 * @return string JSON-encoded array of selected values
	 */
	public function get_checkbox_value( $gf_field, $entry, $field_id ) {
		$checkbox_values = array();
		$choice_number   = 1;

		foreach ( $gf_field->choices as $choice ) {
			// Skip numbers ending in 0 to avoid conflicts (5.1 vs 5.10)
			if ( $choice_number % 10 === 0 ) {
				++$choice_number;
			}

			$input_id      = $field_id . '.' . $choice_number;
			$current_value = rgar( $entry, $input_id );

			if ( ! empty( $current_value ) ) {
				$checkbox_values[] = $current_value;
			}

			++$choice_number;
		}

		if ( empty( $checkbox_values ) ) {
			return '';
		}

		$encoded = wp_json_encode( $checkbox_values );

		return false !== $encoded ? $encoded : '';
	}

	/**
	 * Helper method to get a simple field value from entry.
	 * Used for rank, rating, radio, select, and other simple survey field types.
	 *
	 * @param array $entry The entry
	 * @param int   $field_id The field ID
	 *
	 * @return string The field value or empty string
	 */
	private function get_simple_field_value( $entry, $field_id ) {
		$value = rgar( $entry, $field_id );
		return ! empty( $value ) ? $value : '';
	}


	/**
	 * Update all likert fields in the same table after one is edited.
	 * This ensures that when editing one row in a multi-row likert, all other rows get updated with the latest values.
	 *
	 * @param bool|WP_Error $update_result
	 * @param array         $entry
	 * @param int           $form_id
	 * @param GF_Field|null $gf_field
	 *
	 * @return array Array of field update information
	 */
	public function updated_result( $update_result, $entry = array(), $form_id = 0, ?GF_Field $gf_field = null ) {
		if ( ! $gf_field ) {
			return $update_result;
		}

		$subtype = isset( $gf_field->inputType ) ? $gf_field->inputType : 'survey';

		// For multi-row likert fields, update all rows
		if ( $subtype === 'likert' && ! empty( $gf_field->gsurveyLikertEnableMultipleRows ) && is_array( $gf_field->inputs ) ) {
			$return = array();


			// Get the current value for the entire likert field
			$likert_value = $this->get_likert_value( $gf_field, $entry, $gf_field->id );

			foreach ( $gf_field->inputs as $input ) {
				$input_id = str_replace( '.', '-', $input['id'] );
				
				$return[] = array(
					'selector' => ".gv-inline-editable-field-{$entry['id']}-{$entry['form_id']}-{$input_id}",
					'value'    => $likert_value,
					'data'     => array(
						'display_value' => rgar( $entry, $input['id'] ),
					),
				);
			}

			return $return;
		}

		return $update_result;
	}


}

new GravityView_Inline_Edit_Field_Survey();
