<?php

// autoload-classmap.php @generated by Strauss

$lib = dirname(__FILE__);

return array(
   'GravityWP\Advanced_Merge_Tags\GravityWP\Updater\Plugin_Updater' => $lib . '/gravitywp/license-handler/src/pluginUpdater.php',
   'GravityWP\Advanced_Merge_Tags\GravityWP\LicenseHandler\LicenseHandler' => $lib . '/gravitywp/license-handler/src/LicenseHandler.php',
);